add cpu only rand solver to develop branch.
ORNL/ReSolve pull request #137
Opened 2024-02-15 20:27 UTC by kswirydo

In this branch:
- cpu only randGMRES
- cpu only sketching methods

Rebasing is probably is required...

2024-02-15 23:22 UTC, pelesh requested changes
There are quite a few compiler warnings that should be addressed before this is merged. Use `-Wall -Wconversion -Wextra` flags when compiling to see the warnings and identify potential issues they may cause.

2024-02-15 23:22 UTC, pelesh commented on resolve/LinSolverIterativeRandFGMRES.cpp
>      initial_residual_norm_ = rnorm;
I would revert this change. The code is easier to read if `<<` operators are aligned (this is really nitpicking).

2024-02-15 23:22 UTC, pelesh commented on resolve/LinSolverIterativeRandFGMRES.cpp
> +          << rnorm << "\n";
Alignment of `<<`?

2024-02-15 23:22 UTC, pelesh commented on resolve/LinSolverIterativeRandFGMRES.cpp
> +        << rnorm << "\n";
Alignment of `<<`?

2024-02-15 23:22 UTC, pelesh commented on resolve/LinSolverIterativeRandFGMRES.cpp
> +
Alignment of `<<`?

2024-02-15 23:22 UTC, pelesh commented on resolve/RandSketchingCountSketch.cpp
> +    : memspace_(memspace)
Add doxygen-style comments.

2024-02-15 23:22 UTC, pelesh commented on resolve/RandSketchingCountSketch.cpp
> -    delete h_labels_;
Use doxygen style comments.

2024-02-15 23:22 UTC, pelesh commented on resolve/RandSketchingCountSketch.cpp
>    {
I would update this documentation, if needed, rather than remove it.

2024-02-15 23:22 UTC, pelesh commented on resolve/RandSketchingCountSketch.cpp
> +  /// Setup the parameters, sampling matrices, permuations, etc
Consider updating this documentation instead of removing it.

2024-02-15 23:22 UTC, pelesh commented on resolve/RandSketchingCountSketch.cpp
>    int RandSketchingCountSketch::reset() // if needed can be reset (like when Krylov method restarts)
Same here: I would keep doxygen documentation and update it, if needed.

2024-02-15 23:22 UTC, pelesh commented on resolve/RandSketchingCountSketch.hpp
> +      memory::MemorySpace memspace_;
Consider keeping these doxygen comments instead of removing them. Update, if necessary.

2024-02-15 23:22 UTC, pelesh commented on resolve/cpu/cpuKernels.cpp
> +
Is this function intentionally empty?

2024-02-15 23:22 UTC, pelesh commented on resolve/cpu/cpuKernels.h
> +  void FWHT(index_type M, index_type log2N, real_type* d_Data);
Indentation:
```suggestion
  
  void FWHT_scaleByD(index_type n,
                     const index_type* D,
                     const real_type* x,
                     real_type* y);
  
  void FWHT_select(index_type k,
                   const index_type* perm,
                   const real_type* input,
                   real_type* output);
  void FWHT(index_type M, index_type log2N, real_type* d_Data);
```

2024-02-16 01:04 UTC, pelesh commented
> There are quite a few compiler warnings that should be addressed before this is merged. Use `-Wall -Wconversion -Wextra` flags when compiling to see the warnings and identify potential issues they may cause.

PR #138 (to this branch) addresses the compiler warnings.

2024-02-16 03:25 UTC, kswirydo commented
I fixed formatting issues in [811073f](https://github.com/ORNL/ReSolve/pull/137/commits/811073fdd67ba744c0ba62c521d35ca77954313b)

2024-02-16 03:46 UTC, pelesh approved these changes

2024-02-16 03:50 UTC, merged