add `LinSolverDirectLUSOL`, with initial support for solving Ax = rhs
ORNL/ReSolve pull request #153
Opened 2024-06-10 15:50 UTC by superwhiskers

- adds a function for expanding symmetric matrices only stored as their half
- adds a function for extracting coordinates of nonzeroes from matrices
- documents a deficiency in the Csc class
- modifies the build system to compile fortran code used in LUSOL
- fixes some additional issues made in using index_type/real_type pervasively
- adds a method to the logger class to extract the log level
- adds tests on symmetric matrix expansion

2024-06-10 17:55 UTC, pelesh commented
> * documents a deficiency in the Csc class

@superwhiskers, please create a separate issue rather than adding comments to the code.

2024-06-10 18:57 UTC, pelesh commented
It seems that changes to CMake caused GPU builds to break. An example error message looks like:
```
[ 34%] Building CXX object resolve/matrix/CMakeFiles/resolve_matrix.dir/MatrixHandlerHip.cpp.o
/ccs/home/peles/src/resolve/resolve/resolve/matrix/MatrixHandlerHip.cpp:58:18: error: no matching function for call to 'rocsparse_dcsrmv_analysis'
        status = rocsparse_dcsrmv_analysis(handle_rocsparse,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rocm-5.6.0/include/rocsparse/rocsparse-functions.h:3387:18: note: candidate function not viable: no known conversion from 'index_type *' (aka 'long *') to 'const rocsparse_int *' (aka 'const int *') for 8th argument
rocsparse_status rocsparse_dcsrmv_analysis(rocsparse_handle          handle,
```
I'll investigate more.

2024-06-11 01:17 UTC, pelesh requested changes
Great work! Needs some changes to put it in line with the rest of the Re::Solve code but nothing major.

2024-06-11 01:17 UTC, pelesh commented on resolve/matrix/Csr.cpp
> +        };
Fix line breaks:
```suggestion
    return [=]() -> std::tuple<std::tuple<index_type, index_type, real_type>, bool> {
          if (*j == *n) {
            return {{0, 0, 0}, false};
          }

          while (rows[*i + 1] == *j) {
            (*i)++;
          }

          (*j)++;
          return {{*i, columns[*j - 1], values[*j - 1]}, true};
    };
```

2024-06-11 01:17 UTC, pelesh commented on resolve/matrix/Csr.hpp
> +            elements(memory::MemorySpace);
See comments for `Coo` class.

2024-06-11 01:17 UTC, pelesh commented on resolve/matrix/Sparse.hpp
> +      matrix::elements(matrix::Sparse*);
I would remove this. I don't see a reason to make private functions virtual in this case.

2024-06-11 01:17 UTC, pelesh commented on resolve/matrix/Utilities.cpp
> +  matrix::elements(matrix::Sparse* A)
Fix line breaks:
```suggestion
  std::function<std::tuple<std::tuple<index_type, index_type, real_type>, bool>()> matrix::elements(matrix::Sparse* A)
```

2024-06-11 01:17 UTC, pelesh commented on resolve/matrix/Utilities.hpp
> +    elements(Sparse*);
Fix line breaks: 
```suggestion
    std::function<std::tuple<std::tuple<index_type, index_type, real_type>, bool>()>
 elements(Sparse*);
```

2024-06-11 01:17 UTC, pelesh commented on tests/unit/matrix/LUSOLTests.hpp
> +                                         2., 3., 3., 2., 5., 1., 7., 8., 4.};
Arrange data arrays to follow matrix sparsity structure.
```suggestion
        // Test matrix:
        //
        //     [     2      0      0      0      1      0      3      0      0]
        //     [     0      7      0      5      0      4      0      0      0]
        //     [     1      0      0      0      3      0      0      2      0]
        //     [     0      0      0      3      0      2      0      0      8]
        // A = [     1      0      0      0      0      0      0      0      0]
        //     [     0      4      0      5      0      1      6      0      0]
        //     [     0      0      2      0      2      0      3      3      0]
        //     [     2      0      0      0      0      0      0      5      1]
        //     [     0      0      7      0      8      0      0      0      4]
        std::vector<index_type> rowsA_ = {0, 0, 0,
                                          1, 1, 1,
                                          2, 2, 2,
                                          3, 3, 3,
                                          4,
                                          5, 5, 5, 5,
                                          6, 6, 6, 6,
                                          7, 7, 7,
                                          8, 8, 8};
        std::vector<index_type> colsA_ = {0, 4, 6,
                                          1, 3, 5,
                                          0, 4, 7,
                                          3, 5, 8,
                                          0,
                                          1, 3, 5, 6,
                                          2, 4, 6, 7,
                                          0, 7, 8,
                                          2, 4, 8};
        std::vector<real_type> valsA_ = {2., 1., 3.,
                                         7., 5., 4.,
                                         1., 3., 2.,
                                         3., 2., 8.,
                                         1.,
                                         4., 5., 1., 6.,
                                         2., 2., 3., 3.,
                                         2., 5., 1.,
                                         7., 8., 4.};
```

2024-06-11 01:17 UTC, pelesh commented on tests/unit/matrix/MatrixExpansionTests.hpp
> +            std::vector<std::tuple<index_type, index_type, real_type>> target)
Fix line breaks.

2024-06-11 03:03 UTC, superwhiskers commented on resolve/LinSolverDirectLUSOL.cpp
> +    }
this won't offset each indice of `indc_in` and `indr_in` by one, as is done in the snippet you highlight

2024-06-11 03:08 UTC, superwhiskers commented on resolve/LinSolverDirectLUSOL.cpp
> +    return -inform;
this was to keep the interface in line with what callees may expect, that is, an error is indicated by `return_code < 0`. while the comment was intended to indicate that, it may not have been clear

2024-06-11 03:09 UTC, superwhiskers commented on resolve/LinSolverDirectLUSOL.hpp
> +      /// passed along API boundaries and as a general scratch region
what you added there was what i meant by `Used to hold the nonzeros of matrices passed along API boundaries...`

2024-06-11 13:20 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    }
I am not sure why you need offset but that's besides the point. You can implement offset in the copy functions.

2024-06-11 13:22 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    return -inform;
We don't have a consistent error code policy for Re::Solve yet, so until we get to that point, I would just return LUSOL's `inform` as is.

2024-06-11 13:24 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.hpp
> +      /// passed along API boundaries and as a general scratch region
My suggestion is to use "workspace" as it is commonly used term for this kind of memory allocation in numerical analysis.

2024-06-11 16:24 UTC, pelesh requested changes
To manage the scope of this PR I suggest moving `expand()` function into a separate branch and adding this functionality through a separate pull request once we have functioning device implementation in addition to the current host implementation. See #155. 

The symmetric matrix expansion to a full square matrix is not essential for LUSOL implementation. For this PR it would suffice to return an erro if the matrix is symmetric and not expanded.

2024-06-11 20:42 UTC, pelesh commented
@superwhiskers, I tested this branch and everything looks good. I fixed a couple of minor build warnings in PR #156. I will merge this PR after #156 is merged.

2024-06-11 21:04 UTC, superwhiskers commented
#156 is merged.

2024-06-11 21:31 UTC, pelesh approved these changes

2024-06-11 21:32 UTC, merged