add a LUSOL functionality test
ORNL/ReSolve pull request #164
Opened 2024-06-14 20:47 UTC by superwhiskers

this pull request adds a functionality test for LUSOL. there is one thing that needs to be worked out before this can actually be merged:

- how do we finish implementing symmetric matrix expansion functionality? this is necessary for the integration test to work since LUSOL cannot operate on symmetric matrices stored only as a half (#155)
  - currently, i've added a single method to the `matrix::Coo` class which expands the matrix. this is not permanent and it should be fully expanded upon prior to a merge with equivalent functionality for other matrix types

2024-06-14 20:57 UTC, superwhiskers commented
oh. this also adds comments referencing stuff about extracting L/U factors. i'll remove that so this can be focused only on testing

2024-06-17 16:18 UTC, pelesh requested changes
A good first stab. Here are some suggestions how to proceed.

2024-06-17 16:18 UTC, pelesh commented on resolve/matrix/MatrixHandlerCpu.cpp
> +      index_type* rows = A->getRowData(memory::HOST);
Implement matvec for COO matrices as a static function in the functionality test for now.

2024-06-17 16:18 UTC, pelesh commented on resolve/matrix/Sparse.hpp
> +      int setValueOwnership(bool, memory::MemorySpace);
These are too dangerous methods and we should not implement them. I suggest implementing a [hijacking constructor](https://github.com/ORNL/ReSolve/blob/develop/resolve/matrix/Csr.cpp#L42) as in `Csr` class instead.

2024-06-17 16:18 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  real_type scaled_residual_norm_two = compute_error(error_sum, matrix_handler, vector_handler, matrix_two_path, rhs_two_path);
If you want to do something like this, then the same solver instance has to be passed as the argument to both `compute_error` functions. Otherwise, there is little reason to run tests on two matrices. The `analysis` done at the first call needs to be reused in the second call. I suggest dropping `compute_error` function from this PR and handling it in a separate PR and across all functionality tests.

2024-06-17 16:18 UTC, pelesh commented on resolve/matrix/io.cpp
> +    A->setNnzExpanded((2 * nnz) - n_diagonal);
Use hijacking constructor here.

2024-06-17 17:47 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  std::fill_n(x_data.get(), A->getNumRows(), 1.0);
I think it is better if we use raw pointers for raw data as we want to move it back and forth from GPUs. 
```suggestion
  real_type* x_data = new real_type[A->getNumRows()];
  std::fill_n(x_data, A->getNumRows(), 1.0);
```

2024-06-18 13:10 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  std::fill_n(x_data.get(), A->getNumRows(), 1.0);
We need to make it explicit in the code that raw data should be accessed through raw pointers. This is a CPU-only test, so in this case it does not matter but as the best practice, we should not use unique pointers for the raw matrix and vector data.

2024-06-18 13:14 UTC, pelesh commented on resolve/matrix/Utilities.cpp
> +    //       ...please don't rely on it being predictable
It is unclear to me what this means. In any case, please add notes comments and pre/post conditions in Doxygen style to the new functions.

2024-06-18 17:08 UTC, pelesh requested changes
There are some minor issues that I addressed in my comments.

Newly added `expand()` function needs unit test(s). I suggest we create `MatrixConversionTest.hpp` and `runMatrixConversionTest.cpp` in `tests/unit` directory and implement needed unit tests there.

2024-06-18 17:32 UTC, superwhiskers commented on resolve/matrix/Utilities.cpp
> +      //       have to manually new/memcpy/delete, unfortunately
the note does not make any sense removed from the specific place of the source code it's located in

2024-06-19 18:14 UTC, superwhiskers commented on resolve/matrix/Sparse.hpp
> +      int setValueOwnership(bool, memory::MemorySpace);
see #167

2024-06-21 00:21 UTC, pelesh requested changes
Good progress but some more fixes are needed before this is ready to merge. I left a few comments to that end.

LUSOL test produces some type conversion warnings that need to be fixed.

2024-06-21 00:28 UTC, superwhiskers commented on resolve/matrix/Utilities.hpp
> +     */
no assumption is made. technically, you could pass in a matrix that isn't triangular and it would still work

2024-06-21 00:29 UTC, superwhiskers commented on resolve/matrix/Sparse.cpp
> +  {
i don't really see how that's any better. `setValueOwnership` is just as correct in a plural context

2024-06-21 22:04 UTC, superwhiskers commented
rebased on latest `develop`

2024-06-24 15:09 UTC, cameronrutherford commented
https://github.com/ORNL/ReSolve/blob/lusol-integration-tests/examples/CMakeLists.txt#L140 - might be good to have Lusol be used in the consumer test for testing `resolve~cuda~rocm~klu+lusol`

2024-06-24 15:36 UTC, pelesh commented
> https://github.com/ORNL/ReSolve/blob/lusol-integration-tests/examples/CMakeLists.txt#L140 - might be good to have Lusol be used in the consumer test for testing `resolve~cuda~rocm~klu+lusol`

I agree.  To get there, we need to get LUSOL to work within a refactorization solver strategy, which is outside the scope of this PR.

2024-06-28 15:18 UTC, pelesh commented on resolve/matrix/Utilities.hpp
> +     */
The function should not allow that. If the matrix is not upper- or lower-triangular, this function should return an error. If for some reason non-symmetric matrix was tagged as symmetric, that is a nasty bug, which we need to protect against.

2024-06-28 20:40 UTC, superwhiskers commented on resolve/matrix/Utilities.hpp
> +     */
it's specified as part of the preconditions for each of the expand functions. i can add a debug check that goes away in release builds to catch any bugs that violate it, but i don't see why this should be a general check we do, as the presence of a precondition makes it on the callee to know beforehand

2024-09-20 23:27 UTC, pelesh commented
Closing in favor of #189.

2024-09-20 23:27 UTC, closed without merging