lusol factor extraction
ORNL/ReSolve pull request #178
Opened 2024-07-19 20:46 UTC by superwhiskers

this is in-progress, but i'll leave it open as a draft pull request for now

what remains to be done:
- [ ] rebase on `develop` from `lusol-integration-tests`
- [ ] use already existing `L_` and `U_` member variables instead of allocating new ones
- [ ] constrain size by nsing
- [ ] add tests for factor extraction

2024-07-23 13:29 UTC, superwhiskers commented
wasn't able to solve it with a rebase. i ended up making a new branch locally and cherry-picking the commits from the old one

2024-07-23 17:06 UTC, superwhiskers commented
this should be ready to merge now

2024-07-29 17:55 UTC, pelesh requested changes
The code needs to be better commented. There are some nontrivial indexing patterns and there need to be comments explaining what is being done in main loops in L and U factor getters.

2024-07-29 17:55 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    U_->allocateMatrixData(memory::HOST);
This needs to be better documented. It is not obvious what are luparams 10 and 23.

2024-07-29 17:55 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +        index_type column = qt[indr_[offset] - 1];
```suggestion
      for (index_type destination_offset = rows[row]; destination_offset < rows[row + 1]; destination_offset++) {
        index_type column = qt[indr_[offset] - 1];
```

2024-07-29 17:55 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +          std::swap(columns[swap_offset], columns[swap_offset - 1]);
```suggestion
        for (index_type swap_offset = destination_offset; swap_offset > insertion_offset; swap_offset--) {
          std::swap(columns[swap_offset], columns[swap_offset - 1]);
```

2024-07-29 17:58 UTC, pelesh commented
This is very good work. Apart from commenting code better, this should be ready to merge.

2024-07-29 18:29 UTC, superwhiskers commented on resolve/LinSolverDirectLUSOL.cpp
> +    real_type* values = L_->getValues(memory::HOST);
we have to initialize it to something nonzero for the same reason the new coo2csr implementation (#175) does that. until i've worked out why exactly this works and not zero, this is the only reasonable choice, as any positive value risks conflict with actual column indices

2024-07-30 14:56 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    real_type* values = L_->getValues(memory::HOST);
I think it would be good to investigate if we could implement this with the values of `rows` array initialized to zero, because the logic as implemented now would not work if `index_type` is unsigned integer.

2024-09-11 22:07 UTC, pelesh approved these changes

2024-09-12 18:23 UTC, kswirydo commented on resolve/LinSolverDirectLUSOL.cpp
> +    for (index_type column = 0; column < diagonal_bound; column++) {
is this supposed to sort columns through bubble sort type algorithm?

2024-09-12 18:23 UTC, kswirydo commented on resolve/LinSolverDirectLUSOL.cpp
> +    p_ = nullptr;
doesnt this need to be deleted before becoming a nullptr?

2024-09-12 18:23 UTC, kswirydo commented on resolve/LinSolverDirectLUSOL.cpp
> +    q_ = nullptr;
same with this, and other variables/

2024-09-12 19:19 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    if (rhs->getSize() != m_ || x->getSize() != n_ || !is_factorized_) {
To be tracked in #183.

2024-09-12 19:19 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    for (index_type column = 0; column < diagonal_bound; column++) {
I believe this loop just adds ones to the diagonal of L.

2024-09-12 19:24 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    p_ = nullptr;
It does get deleted first.

2024-09-12 19:28 UTC, merged

2024-09-13 06:26 UTC, superwhiskers commented on resolve/LinSolverDirectLUSOL.cpp
> +    for (index_type column = 0; column < diagonal_bound; column++) {
to elaborate, this loop corrects the size of each column segment by the lengths necessary to accommodate an extra element in itself and all previous columns. it then inserts the one at the end of the column's allocated space, since it
1. will always be the last element in a sorted column
2. would add extra computational overhead if it were placed at the beginning (since it would incur an extra n - 1 swaps or something like that) to get the column sorted

sorting of the elements lusol writes to the l factor is done in the next loop, and that is done with a kind of insertion sort, as the comment above it states

2024-09-13 12:48 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
> +    for (index_type column = 0; column < diagonal_bound; column++) {
Thanks for helpful additional explanations, @superwhiskers.