Add functionality test for LUSOL
ORNL/ReSolve pull request #189
Opened 2024-09-20 23:26 UTC by pelesh

The test is based on KLU functionality test but because LUSOL does not have refactorization option, the test simply performs two full factorizations for different matrices.

This is based on @superwhiskers test in #164.

Resolves #158.

2024-09-25 15:52 UTC, stonecoldhughes requested changes
Overall, this file is structured very clearly. Separating the code into more functions, incorporating data files without hardcoded paths, avoiding manual memory management with new/delete, and adding some more high level comments that provide more insight into exactly what is going on with the validation sections would improve it. I selected the "Submit feedback that must be addressed before merging." option before submitting this review: if you prefer, I can instead select  "Submit general feedback without explicit approval" in future reviews.

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +using namespace ReSolve::constants;
Some low-priority nit picking - I think it is slightly better to avoid "using" whenever possible. While it does make the code less verbose, I think it tends to make the code more difficult to understand, since the types in the code are not fully written out where they occur. Again, this is not a high priority suggestion and many disagree.

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +static int coo2csr(ReSolve::matrix::Coo* A_coo, ReSolve::matrix::Csr* A_csr, ReSolve::memory::MemorySpace memspace);
Is it possible to avoid this forward declaration by including headers differently? Forward declarations are very helpful sometimes, but they introduce a new place for a bug to hide: https://stackoverflow.com/questions/14381348/what-are-the-dangers-of-forward-declarations

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  std::string matrix_one_path = data_path + "data/matrix_ACTIVSg200_AC_10.mtx";
if this data file's enclosing directory structure changes, it could crash the program if the developer forgets to update this path. It may be less error prone to configure input files differently using the build system: CMake's https://cmake.org/cmake/help/latest/command/configure_file.html. Internally, a preprocessor variable can be set during build to contain the correct path to the data. These #defined variables can then be included in a header file. The argc/argv feature allows the base path of the data directory to be configured a bit more easily, but argc and argv can be bug prone if there is not lots of logic to ensure well-formed input. It does not appear like such logic is available here.

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  if (!matrix_file.is_open()) {
now I see that there is some basic checking, this is good

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +
all the code above this line appears to be "setup" code just for creating data structures etc. Perhaps it would improve readability to encapsulate this "setup" functionality in a separate function, and clearly delineate which tasks belong in the "setup" phase

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  delete[] rhs;     // rhs    = nullptr;
these delete statements can be safely removed if smart pointers are used instead of raw pointers: https://en.cppreference.com/w/cpp/memory/unique_ptr

it's always a good idea to use smart pointers because they guarantee that memory is freed once the pointer goes out of scope, effectively insuring against memory leaks.

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +
the code below this line appears to be "post-processing" type functionality where the output is evaluated for correctness. Similar to the "setup" code, could this be separated into a dedicated function to improve delineation of responsibility and improved readability?

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  matrix_handler.setValuesChanged(true, ReSolve::memory::HOST);
Request equation-style comments in the code section below this line: while it is clear that this code calculates a residual, there is a lot going on and it's not immediately obvious what.

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  A = std::unique_ptr<ReSolve::matrix::Coo>(ReSolve::io::createCooFromFile(matrix_file));
this is good; "A" will be deallocated automatically, the developer does not have to worry with memory leaks

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +int coo2csr(ReSolve::matrix::Coo* A_coo, ReSolve::matrix::Csr* A_csr, ReSolve::memory::MemorySpace memspace)
This type of conversion is surely useful elsewhere in the code - should we consider putting it in a common utilities header?

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  index_type* row_csr = new index_type[n + 1];
consider using unique_ptr here as well?

2024-09-25 15:52 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  error_sum += lusol.setup(A.get());
is this another "setup/analyze/factorize/solve" step different from the first one above in the same file? A bit more commentary might be helpful here, as I'm not sure how this section and what follows fits into the grand scheme.

2024-09-25 16:49 UTC, pelesh commented on resolve/LinSolverDirectLUSOL.cpp
>      a_ = new real_type[lena_];
As I wrote in the comments above there is little we can do about this, because LUSOL does not have symbolic analysis to compute sparsity pattern of L and U factors. L and U factors combined are typically _denser_ than the original matrix A = LU, so we have to allocate workspace that is larger than the storage needed for A. Having that storage 20x the storage for the matrix A is probably an overkill but it will allocate a sufficient space for all but extreme cases. We will be wasting some memory for sure, but this the solver will work correctly.

Mind you LUSOL is a _legacy_ code and does not have all the features more recent linear solvers have. At this point, we don't plan to use LUSOL in applications. It is added to Re::Solve for research purposes.

2024-09-25 16:57 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +using namespace ReSolve::constants;
I agree with you that we should avoid `using` when possible. In this particular case, the scope of the `using` is in this file only and it actually helps readability of the code quite a bit. The `namespace constants` contains simple constants such as `one`, `sqrt2`, etc.

2024-09-25 16:59 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +static int coo2csr(ReSolve::matrix::Coo* A_coo, ReSolve::matrix::Csr* A_csr, ReSolve::memory::MemorySpace memspace);
These are just prototypes for static functions. The alternative option is to _define_ static functions before the calling `main` function. I like better to start the code with `main` but this is just a matter of taste.

2024-09-25 17:02 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  std::string matrix_one_path = data_path + "data/matrix_ACTIVSg200_AC_10.mtx";
This is how we handle data for functionality tests and I agree there is a lot of room for improvement there. Please create a separate issue with your suggestions how to handle this better.

2024-09-25 17:36 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +
Can you suggest how to do that in a separate issue? It would be good to have a set of common utility functions for all functionality tests. This is out of scope for this PR, though.

2024-09-25 17:40 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +
Similar as for the comment earlier -- please create an issue with a proposal how to create a set of common utility functions for functionality tests. This PR follows the standard pattern for functionality test that involves a lot of copy-paste-tweak coding, which is not sustainable.

This is out of scope for this PR, though.

2024-09-25 17:43 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +int coo2csr(ReSolve::matrix::Coo* A_coo, ReSolve::matrix::Csr* A_csr, ReSolve::memory::MemorySpace memspace)
We could but it is low priority right now. This utility is used for LUSOL only because it has uncommon input requirements. It is unlikely we'll need this elsewhere in the near future.

2024-09-25 17:51 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  delete[] rhs;     // rhs    = nullptr;
We plan to use raw pointers for matrix/vector data in the future because we move that data frequently between CPU and GPU. In such setting, smart pointers solve only half of the problem at the expense of adding some cumbersome coding to extract raw pointers to pass them to memory management functions. Using smart pointers for Re::Solve classes would be desirable, see #88.

2024-09-25 17:52 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  index_type* row_csr = new index_type[n + 1];
See earlier comment and #88.

2024-09-25 20:02 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  error_sum += lusol.setup(A.get());
Addressed in [9a50a41](https://github.com/ORNL/ReSolve/pull/189/commits/9a50a414219487dd59a1844d1275aebfefe9151a)

2024-09-25 20:03 UTC, pelesh commented on tests/functionality/testLUSOL.cpp
> +  matrix_handler.setValuesChanged(true, ReSolve::memory::HOST);
Addressed in [9a50a41](https://github.com/ORNL/ReSolve/pull/189/commits/9a50a414219487dd59a1844d1275aebfefe9151a)

2024-09-26 15:20 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +using namespace ReSolve::constants;
since the using directive is only in this file, and for constants which are already pretty self-documenting, this seems like a fine usage of "using"

2024-09-26 15:30 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  std::string matrix_one_path = data_path + "data/matrix_ACTIVSg200_AC_10.mtx";
https://github.com/ORNL/ReSolve/issues/192

2024-09-26 15:33 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +
https://github.com/ORNL/ReSolve/issues/193

2024-09-26 15:34 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +
https://github.com/ORNL/ReSolve/issues/193

2024-09-26 15:40 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  delete[] rhs;     // rhs    = nullptr;
This is an issue related to the heterogeneous nature of split CPU/GPU memory space. For now, being careful to delete raw pointers is the most straightforward option

2024-09-26 15:41 UTC, stonecoldhughes commented on tests/functionality/testLUSOL.cpp
> +  std::string matrix_one_path = data_path + "data/matrix_ACTIVSg200_AC_10.mtx";
https://github.com/ORNL/ReSolve/issues/192

2024-09-26 15:45 UTC, stonecoldhughes approved these changes

2024-09-26 15:54 UTC, merged

2024-10-17 08:44 UTC, superwhiskers commented on resolve/LinSolverDirectLUSOL.cpp
>      a_ = new real_type[lena_];
it's entirely possible to handle the insufficient memory condition gracefully. while i couldn't find a way to resume lu factorization, lusol will report through the integer parameter array the minimum needed space to continue and you can restart factorization from scratch with a larger lena