Matrix handler now checks in the background if the matrix is CSR.
ORNL/ReSolve pull request #190
Opened 2024-09-24 22:38 UTC by pelesh

Since only CSR format is supported by the `MatrixHandler` methods for matrix-vector product and matrix norm, these methods will now check if the matrix is CSR and, if not, return an error. When (if) `MatrixHandler` supports other sparse formats, we can add switch to those methods to perform computations specific to the (supported) input matrix  format.

This PR:
- Removes input argument from `matvec` method specifying the matrix format.
- Adds member variable with matrix format ID to `matrix::Sparse` class. Each derived class (`Csr`, Csc`, etc.) sets this ID at construction. This allows `matvec` and `matrixNorm` to check matrix format "under the hood".
- Addresses #180.
- Updates examples and tests with new `MatrixHandler::matvec` interface.

2024-09-25 16:12 UTC, stonecoldhughes requested changes
Removing the "csr" parameter is a really good improvement here. Minor comments include weighing the benefits of static assertions versus conditionals for checking ; using the "using" directive; extending a variable name to be more descriptive

2024-09-25 16:12 UTC, stonecoldhughes commented on resolve/matrix/Sparse.hpp
> +      enum SparseFormat{TRIPLET, COMPRESSED_SPARSE_ROW, COMPRESSED_SPARSE_COLUMN};
a scoped enumeration instead of this unscoped enumeration would provide more rigorous type checking: that may or may not be desired. Adds a little bit more rigor at the expense of a little more verbosity.

2024-09-25 16:12 UTC, stonecoldhughes commented on resolve/matrix/MatrixHandlerCpu.cpp
> +    if (A->getSparseFormat() != matrix::Sparse::COMPRESSED_SPARSE_ROW) {
an "assert" statement could replace conditionals like these if there is ever a desire to disable/enable the checking; while turning off checks is unsafe, there may be performance benefits if these conditionals end up being called a lot. The top answer on this post helps shed more light on the two avenues: https://stackoverflow.com/questions/11468899/any-benefit-of-using-assert-instead-of-using-a-simple-if

2024-09-25 18:11 UTC, pelesh commented on resolve/matrix/MatrixHandlerCpu.cpp
> +    if (A->getSparseFormat() != matrix::Sparse::COMPRESSED_SPARSE_ROW) {
This check will be replaced with a switch statement if/when we implement methods that work with formats other than CSR. I added a note to that end in method comments.

In the meantime, I replaced `if` with `assert` as you suggested.

2024-09-25 18:13 UTC, pelesh commented on resolve/matrix/Sparse.hpp
> +      enum SparseFormat{TRIPLET, COMPRESSED_SPARSE_ROW, COMPRESSED_SPARSE_COLUMN};
Please create a separate issue to discuss this. I believe this will be applicable to other `enum`s in the code.

2024-09-25 18:15 UTC, pelesh commented on resolve/matrix/Coo.cpp
>      if ((memspaceSrc == memory::HOST)   && (memspaceDst == memory::HOST))  { control = 0;}
Good catch!

2024-09-25 18:15 UTC, pelesh commented on resolve/matrix/Coo.cpp
>      using namespace memory;
Removed!

2024-09-25 18:19 UTC, pelesh commented on resolve/matrix/Coo.cpp
> +    sparse_format_ = TRIPLET;
Triplet and COO are synonyms. I used "triplet" in this case to prevent possible confusion with class name `Coo`. I would leave it as is.

2024-09-25 18:43 UTC, pelesh commented on resolve/matrix/MatrixHandlerCpu.cpp
> +    if (A->getSparseFormat() != matrix::Sparse::COMPRESSED_SPARSE_ROW) {
See [67915e1](https://github.com/ORNL/ReSolve/pull/190/commits/67915e10f2a084e418c2fb2739037be6e370879f)

2024-09-25 18:43 UTC, pelesh commented on resolve/matrix/Coo.cpp
>      if ((memspaceSrc == memory::HOST)   && (memspaceDst == memory::HOST))  { control = 0;}
See [67915e1](https://github.com/ORNL/ReSolve/pull/190/commits/67915e10f2a084e418c2fb2739037be6e370879f)

2024-09-26 14:51 UTC, stonecoldhughes commented on resolve/matrix/Coo.cpp
> +    sparse_format_ = TRIPLET;
Sounds like "TRIPLET" is standard terminology in the field, so this name is fine as it is

2024-09-26 15:03 UTC, stonecoldhughes commented on resolve/matrix/Sparse.hpp
> +      enum SparseFormat{TRIPLET, COMPRESSED_SPARSE_ROW, COMPRESSED_SPARSE_COLUMN};
https://github.com/ORNL/ReSolve/issues/191

2024-09-26 15:45 UTC, stonecoldhughes approved these changes

2024-09-26 21:13 UTC, merged