This fixes cmake for permutation in HyKKT
ORNL/ReSolve pull request #209
Opened 2024-12-27 23:11 UTC by shakedregev

2024-12-28 00:41 UTC, shakedregev commented
Added some fixes for CUDA

2025-01-03 23:47 UTC, shakedregev commented
Successfully rebased with respect to `hykkt-dev` to resolve conflicts.

2025-01-07 19:20 UTC, pelesh commented on resolve/CMakeLists.txt
> +add_subdirectory(hykkt)
HyKKT requires AMD from SuiteSparse library, so this should read something like:
```suggestion
# Add HyKKT solver
if(RESOLVE_USE_KLU)
  add_subdirectory(hykkt)
endif()
```

2025-01-07 19:54 UTC, pelesh requested changes
This is a very nice first step for porting HyKKT to Re::Solve. I am converting this to a draft PR as it may need a bit more work to get ready to merge. Some immediate actions that I would suggest:
- Use `ReSolve` name space for all HyKKT classes.
- Consider keeping HyKKT specific code in `hykkt` namespace within `ReSolve`.
- Make sure CI tests pass. Currently there seem to be some issues due to incorrect include paths.

2025-01-07 20:04 UTC, shakedregev commented
> This is a very nice first step for porting HyKKT to Re::Solve. I am converting this to a draft PR as it may need a bit more work to get ready to merge. Some immediate actions that I would suggest:
> 
> * Use `ReSolve` name space for all HyKKT classes.
> * Consider keeping HyKKT specific code in `hykkt` namespace within `ReSolve`.
> * Make sure CI tests pass. Currently there seem to be some issues due to incorrect include paths.

1. I assume you mean more than just using it, right? Should I replace the vectors and matrices with the Resolve objects?
2. ok, though this is usually the entire file
3. Made some changes, let's see if it passes

2025-01-13 14:00 UTC, shakedregev commented
@pelesh - I merged your other branch into this after testing on Frontier and Nvidia machines. Please let me know if any more changes are needed here.

2025-01-14 03:49 UTC, pelesh requested changes
Looks good! Some minor corrections are needed before merging:
- Complete all Doxygen comments. Make sure there are no empty fields.
- Use `switch` statement instead of preprocessor directives to select sort method.
- I believe file `runMatrixPermutationTests.cpp` can be removed. It seems it was added accidentally.

2025-01-14 03:49 UTC, pelesh commented on resolve/hykkt/Permutation.cpp
> +      delete [] perm_map_jac_tr_;
Nitpicking: I suggest we replace this with private method to delete workspace.

2025-01-14 03:49 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +#endif
Since we already have an enum for different permutation methods, we could use a switch statement here and select permutation method at runtime.

2025-01-14 03:49 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +     * @param[out] perm_map
Describe parameters.

2025-01-14 03:49 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +     * @param[out] rev_perm
Describe parameters.

2025-01-14 03:49 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +                    int* perm_map)
Alignment:
```suggestion
    void makeVecMapR(int n, 
                     const int* rows, 
                     const int* cols, 
                     const int* perm, 
                     int* perm_rows, 
                     int* perm_cols, 
                     int* perm_map)
```

2025-01-14 03:49 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +#endif
Same as before -- use switch statement to select sort method.

2025-01-14 03:49 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.hpp
> +    */
Remnants of doxygen docs for individual kernels can be removed from here.

2025-01-14 03:49 UTC, pelesh commented on tests/unit/hykkt/HykktPermutationTests.hpp
> + *
Document tests.

2025-01-14 03:49 UTC, pelesh commented on tests/unit/hykkt/runHykktPermutationTests.cpp
> + */
Document test runners.

2025-01-14 03:49 UTC, pelesh commented on tests/unit/matrix/runMatrixPermutationTests.cpp
> +
What is this file? I think it can be removed.

2025-01-14 22:09 UTC, shakedregev commented on tests/unit/matrix/runMatrixPermutationTests.cpp
> +
Agreed, must be a failed legacy attempt.

2025-01-15 14:41 UTC, shakedregev commented
@pelesh - I've addressed your comments, please let me know if you have any more or if we are ready to merge.

2025-01-15 15:27 UTC, pelesh approved these changes
I added a few nitpicking comments that would be good to address, but I think we can merge this.

2025-01-15 15:27 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +     * @param[in] j
A few more undocumented parameters. It would be good to have brief descriptions here for completeness.

2025-01-15 15:27 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +     */
See previous comment on undocumented parameters.

2025-01-15 15:27 UTC, pelesh commented on resolve/hykkt/cpuPermutationKernels.cpp
> +     */
Same as above.

2025-01-15 16:46 UTC, merged