Draft: Doxygen
ORNL/ReSolve pull request #44
Opened 2023-10-31 18:43 UTC by jaelynlitz

2023-11-17 20:56 UTC, ryandanehy commented
Documentation lives here [https://ornl.github.io/ReSolve/](https://ornl.github.io/ReSolve/)

To see the doxygen based documentation check out the source documentation page. 

These docs will be built on every pr automatically so that contributors can see their additions.

Options to futher explore:
Direct links to certaind oxygen pages on the main read the docs page.
More page and content to add. 

PS: This is made via github action I created here: [https://github.com/ryandanehy/sphinx-doxygen](https://github.com/ryandanehy/sphinx-doxygen ) Therefore it should be incredibly easy to apply this method of documentation to other repos.

2023-11-20 21:36 UTC, ryandanehy commented
@pelesh

2023-11-20 22:24 UTC, pelesh commented
@ryandanehy, this is great! A couple of suggestions:
- Provide links to readthedocs at main README file.
- Similarly to doxygen API docs.
- For some reason, doxygen docs are not built with doxygen awesome stylesheets. Could we fix that.

Other than these minor issues, this looks very good.

2023-11-20 22:27 UTC, pelesh commented
Also, to add to the list above, Doxygen needs to be built with graphviz support, so it can draw UML diagrams.

2023-11-20 22:36 UTC, pelesh commented
@ryandanehy, it seems that as we are providing Doxygen input file template, we are overriding Doxygen options set in CMake. I'll take a look. Ideally, all of our preferred options should be in the input file template. That will make CMake config cleaner, as well.

2023-11-21 17:39 UTC, ryandanehy commented
@pelesh I think I made the changes you requested. Lmk what you think.

2023-11-21 20:39 UTC, pelesh requested changes
There are some minor changes to make, most importantly Doxygen options selected in the CMake file should be placed in the `Doxyfile.in` as my understanding is it is used to generate Doxygen docs (at least based on `conf.py` file.

Also, in the Doxygen docs, UML files are not generated or at least I don't see them.

2023-11-21 20:39 UTC, pelesh commented on CMakeLists.txt
> +
I am not sure if you need these instructions if you are using doxygen configuration file template.

2023-11-21 20:39 UTC, pelesh commented on cmake/ReSolveAddLibrary.cmake
> +#]]
Is this within the scope of this PR? There is no harm in keeping it, but I am just curious if this is needed for the documentation.

2023-11-21 20:39 UTC, pelesh commented on resolve/matrix/Csr.cpp
> +} // namespace ReSolve
Why did this file change?

2023-11-21 20:39 UTC, pelesh commented on resolve/matrix/Sparse.cpp
> +}} // namespace ReSolve::matrix
This should not have been touched by documentation PR.

2023-11-21 22:43 UTC, ryandanehy commented on cmake/ReSolveAddLibrary.cmake
> +#]]
It is not. I forgot that I started to work on this issue in hackthon i can get rid of it.

2023-11-21 22:45 UTC, ryandanehy commented on resolve/matrix/Csr.cpp
> +} // namespace ReSolve
It was accidnetally saved when I was testing doxygen. it just deleted an end of file space. I can change it back

2023-11-21 22:45 UTC, ryandanehy commented on resolve/matrix/Sparse.cpp
> +}} // namespace ReSolve::matrix
It was accidentally saved when I was testing doxygen. it just deleted an end of file space. I can change it back

2023-11-21 22:48 UTC, pelesh commented on docs/conf.py
> +author = 'Kasia Świrydowicz, Slaven Peles'
Copyright belongs to UT Battelle and Battelle Memorial Institute.
```suggestion
copyright = '2023, UT-Battelle, LLC, and Battelle Memorial Institute'
author = 'Kasia Świrydowicz, Slaven Peles'
```

2023-11-22 00:41 UTC, cameronrutherford commented on docs/doxygen/Doxyfile.in
> +HTML_EXTRA_STYLESHEET  = "doxygen-awesome-css/doxygen-awesome.css"
@ryandanehy here

2023-11-22 15:00 UTC, ryandanehy commented
@pelesh  is this what you were going for?
https://ornl.github.io/ReSolve/doxygen/html/dir_5136c54ba47d989d05eb394194374e6c.html

2023-11-22 16:52 UTC, cameronrutherford commented
> @pelesh  is this what you were going for?
> 
> https://ornl.github.io/ReSolve/doxygen/html/dir_5136c54ba47d989d05eb394194374e6c.html 

Looks much better!!

2023-11-23 01:16 UTC, pelesh commented
@ryandanehy, let me please review once more. There are a few things such as copyright statement that needs to be fixed, but all the main features are in the PR and working. Thanks for the great work and figuring out all pathing nightmares ;).

2023-11-23 03:30 UTC, pelesh approved these changes
This is a good first attempt at getting documentation for ReSolve. There are several minor issues that are best addressed through separate PR(s).

2023-11-23 03:30 UTC, pelesh commented on docs/doxygen/Doxyfile.in
> +HTML_COLORSTYLE        = LIGHT # required with Doxygen >= 1.9.5
These options are appended to the end of the Doxygen file instead of changed where they were first defined. Probably a good idea to clean up the doxygen configuration template file.

2023-11-23 03:30 UTC, pelesh commented on docs/doxygen/index.rst
> +`LinAlgWorkspaceCpu_8cpp documentation <./html/LinAlgWorkspaceCpu_8cpp.html>`_
I am not sure why these specific links were added here, but we can edit this later.

2023-11-23 03:30 UTC, pelesh commented on docs/sphinx/Makefile
> +BUILDDIR      = _build
Where is this Makefile used?

2023-11-23 03:30 UTC, pelesh commented on docs/sphinx/coding_guide/index.md
> +If an output is needed (for example, a warning needs to be displayed), use `std::cout` and not `printf` as shown below. There should be a space before and after each `<<`.
Why is this file copied here? Moreover, it seems that the original contributing instructions are still at the same location as they were before making this a duplicate. We need to decide where we will kep this documentation and have a single place to keep it.

2023-11-23 03:30 UTC, pelesh commented on docs/sphinx/licenses.md
> +sublicense copies of the Software.
Similar to coding style guidelines, the license file is duplicate (actually a triplicate) with copies in `LICENSE.md` file in the ReSolve root directory and markdown and rest versions in `docs/sphinx` directory. We need a single place where we will keep this document.

2023-11-23 03:36 UTC, pelesh commented on docs/doxygen/Doxyfile.in
> +HTML_COLORSTYLE        = LIGHT # required with Doxygen >= 1.9.5
See #78

2023-11-23 03:36 UTC, pelesh commented on docs/doxygen/index.rst
> +`LinAlgWorkspaceCpu_8cpp documentation <./html/LinAlgWorkspaceCpu_8cpp.html>`_
See #79

2023-11-23 03:39 UTC, pelesh commented on docs/sphinx/coding_guide/index.md
> +If an output is needed (for example, a warning needs to be displayed), use `std::cout` and not `printf` as shown below. There should be a space before and after each `<<`.
See #80

2023-11-23 03:39 UTC, pelesh commented on docs/sphinx/licenses.md
> +sublicense copies of the Software.
See #80

2023-11-23 03:42 UTC, pelesh commented on docs/sphinx/Makefile
> +BUILDDIR      = _build
See #81

2023-11-23 03:44 UTC, merged