Refactor CMake
ORNL/ReSolve pull request #59
Opened 2023-11-02 19:28 UTC by cameronrutherford

- removes blanket `include_directories` everywhere (closes #15)
- adds custom library macro to support shared/static libraries (closes #46)

2023-11-02 20:05 UTC, cameronrutherford commented on examples/CMakeLists.txt
> +# TODO - have an outer loop that adds a unique consumer test for each backend supproted
@pelesh please create an issue that helps clarify this - if someone builds with CUDA and HIP, should we test linking against one? Both? Should we just leave it as is and remove this TODO comment?

2023-11-02 20:26 UTC, cameronrutherford commented
Ready to merge as change is atomic and tests are passing

2023-11-02 20:40 UTC, cameronrutherford commented on examples/resolve_consumer/CMakeLists.txt
> +target_link_libraries(consume.exe PUBLIC ReSolve::ReSolve)
```suggestion
target_link_libraries(consume.exe PRIVATE ReSolve::ReSolve)
```

2023-11-02 20:43 UTC, cameronrutherford commented on examples/CMakeLists.txt
> +# TODO - have an outer loop that adds a unique consumer test for each backend supproted
See #61

2023-11-03 00:48 UTC, pelesh requested changes
When running `make test_install` the consumer app build fails with following error:
```
-- HIP include directories: /opt/rocm-5.6.0/include
-- Configuring done
CMake Error at /ccs/home/peles/local/resolve-frontier/share/resolve/cmake/ReSolveTargets.cmake:64 (set_target_properties):
  The link interface of target "ReSolve::resolve_hip" contains:

    roc::rocblas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /ccs/home/peles/local/resolve-frontier/share/resolve/cmake/ReSolveConfig.cmake:5 (include)
  CMakeLists.txt:10 (find_package)
```
I think this needs just a little tweak to get it to work.

Otherwise changes look good!

2023-11-03 00:54 UTC, closed without merging