Randomized solver (both cuda and hip)
ORNL/ReSolve pull request #83
Opened 2023-11-28 05:12 UTC by kswirydo

Working randomized GMRES with preconditioner. You can make it into FGMRES by setting flexible to 1.

Caveat: the cuda version uses ancient version of triangular solve `cusparseDcsrsv2` (I am using ILU0 preconditioner that needs triangular solve); despite my best efforts, I was not able to get the more modern version, `cusparseSpSV` to generate correct results. Hence, the code generates correct results... but uses older version of triangular solve so it compiles with tones of warnings on `deprecated` CUDA functions. I followed [this example](https://github.com/NVIDIA/cuda-samples/blob/e8568c417356f7e66bb9b7130d6be7e55324a519/Samples/4_CUDA_Libraries/conjugateGradientPrecond/main.cpp) from cuda samples to no avail. See previous commits.

What has been added:
- Two randomized classes (for fast Walsh Hadamard tranform based sketching and for Count-Sketch based sketching); cuda and hip kerneles for both,
- Randomized solver that deploys Theta (sketching).
- A cuda and hip-based examples.

To test, run `runResolveOneMatrix` with matrix of your choice (I tested with `vas_stokes_1M` from SuiteSparse).

2023-11-28 17:06 UTC, pelesh requested changes
This is great work! My main suggestion is to have functionality tests for CUDA and HIP backends implemented and added to this PR. There are a few minor issues I also mentioned in this PR.

2023-11-28 17:08 UTC, pelesh commented
Ascent build fails with following error message:
```
Building CUDA object resolve/cuda/CMakeFiles/resolve_backend_cuda.dir/MemoryUtils.cu.o
/gpfs/wolf/proj-shared/csc359/ci/489235/resolve/cuda/cudaKernels.cu(157): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
1 error detected in the compilation of "/gpfs/wolf/proj-shared/csc359/ci/489235/resolve/cuda/cudaKernels.cu".
make[2]: *** [resolve/cuda/CMakeFiles/resolve_backend_cuda.dir/build.make:76: resolve/cuda/CMakeFiles/resolve_backend_cuda.dir/cudaKernels.cu.o] Error 1
```

2023-11-28 18:15 UTC, kswirydo commented
You need cuda architecture 7.0 (or 70) to build this. Othewise atomicAdd is defined only for floats but not for doubles. Default is 5.2 somehow.

2023-11-28 18:22 UTC, kswirydo commented on resolve/LinSolverDirectRocSparseILU0.cpp
> +    mem_.allocateBufferOnDevice(&buffer_, buffer_size);
if you dont cast, you get warnings. I think two values are ints and one is size_t or something like this.

2023-11-28 18:25 UTC, kswirydo commented on resolve/hip/hipKernels.hip
> +
I agree with this (I didnt optimize these kernels really ). The problem is that we have a lot kernels and each requires separate parameters so using consts/defines is probably not the way to do it(?).

2023-11-28 18:25 UTC, kswirydo commented on profile.sysinfo.txt
> +==========
idk what is it doing in commit to begin with :P

2023-11-28 18:28 UTC, kswirydo commented on resolve/hip/hipKernels.hip
> +namespace cg = cooperative_groups;
this particular constant would only change if you are allowed to have more than 1024 threads per block.

2023-11-28 18:37 UTC, kswirydo commented on profile.sysinfo.txt
> +==========
I removed in a commit

2023-11-28 18:37 UTC, kswirydo commented on runResolveOneMatrix
> +
Documented this so it can be used by others

2023-11-28 19:26 UTC, cameronrutherford commented
I don't know why PNNL tests aren't running, but now ORNL tests are passing @ryandanehy

2023-11-28 20:19 UTC, pelesh commented on resolve/cuda/cudaKernels.cu
> +namespace cg = cooperative_groups;
To be tracked in #85.

2023-11-28 20:19 UTC, pelesh commented on resolve/hip/hipKernels.hip
> +namespace cg = cooperative_groups;
To be tracked in #85.

2023-11-28 20:20 UTC, pelesh commented on resolve/hip/hipKernels.hip
> +
To be tracked in #85.

2023-11-29 03:52 UTC, kswirydo commented on resolve/LinSolverIterativeRandFGMRES.hpp
> +                                 GramSchmidt*   gs,
I was so excited that it worked finally  that I forgot to indent :D

2023-11-29 03:53 UTC, kswirydo commented on resolve/RandSketchingFWHT.cpp
> +#endif
So what is your suggestion - i.e., we need Theta function (for instance) defined in cudaKernels and hipKernels - what is a better way to do it?

2023-11-29 03:54 UTC, kswirydo commented on resolve/RandSketchingFWHT.hpp
> +#include <resolve/vector/Vector.hpp>
so how do I get access to the vector ?

2023-11-29 04:47 UTC, pelesh commented on resolve/RandSketchingFWHT.cpp
> +#endif
Let's discuss this outside this PR. See #87.

2023-11-29 04:50 UTC, pelesh commented on resolve/RandSketchingFWHT.hpp
> +#include <resolve/vector/Vector.hpp>
I would use forward declaration in the header file and include `Vector.hpp` in the source file.

2023-11-29 06:24 UTC, kswirydo commented on resolve/RandSketchingFWHT.hpp
> +#include <resolve/vector/Vector.hpp>
I did as you suggested, see newest commit

2023-11-29 06:27 UTC, kswirydo commented
My lastest commit has a working version of cuda 11+ compatible SpSV triangular solve in ILU0 class. I also applied Slaven's dependency comments to 2 files.

2023-11-29 14:53 UTC, cameronrutherford requested changes
Looking good!

2023-11-29 14:53 UTC, cameronrutherford commented on examples/r_randGMRES.cpp
> +  real_type* x   = nullptr;
This is endemic to ExaGO and HiOp, but I would be curious if we could get away from managing raw pointers like this, and have more of our examples use more modern C++ resource management techniques with shared/unique pointers where absolutely necessary, and then just having non-pointer variables here that are cleaned up without `delete`

2023-11-29 14:53 UTC, cameronrutherford commented on examples/r_randGMRES.cpp
> +  real_type* x   = nullptr;
This same commend applies to other examples as well, and probably large amounts of the code...

2023-11-29 14:53 UTC, cameronrutherford commented on examples/CMakeLists.txt
> +  set(installable_executables ${installable_executables} klu_glu.exe klu_rf.exe klu_rf_fgmres.exe klu_glu_values_update.exe gmres_cusparse_rand.exe)
Not necessary to change, but CMake has in built list operands that are a little easier to read - https://cmake.org/cmake/help/latest/command/list.html

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/CMakeLists.txt
> +    LinSolverDirectCuSparseILU0.hpp
CUDA / ROCm specific sources should only be added conditionally to lists like this

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverDirectCuSparseILU0.cpp
> +                                         vector_type* )
If we were to move away from pointers in driver code, I think function signatures would stay the same, we would just be passing references instead

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverDirectCuSparseILU0.hpp
> +      ~LinSolverDirectCuSparseILU0();
Would probably need a copy / move constructor in many places to move away from pointers everywhere

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverDirectRocSparseILU0.cpp
> +    mem_.allocateBufferOnDevice(&buffer_, buffer_size);
+1 to `std::max`...

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverIterativeFGMRES.cpp
> +    printf("it 0: norm %16.16e \n", rnorm);
Need to make sure these are conditionally disable-able for #2

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverIterativeFGMRES.cpp
> +        printf("it %d: norm %16.16e \n",it, rnorm);
Same here

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverIterativeFGMRES.hpp
> +    bool getFlexible();
```suggestion
    bool getFlexible() const;
```

We should probably make these pure getters const to reflect their behavior.

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverIterativeFGMRES.hpp
>      real_type getInitResidualNorm();
```suggestion
    real_type getFinalResidualNorm() const;
    real_type getInitResidualNorm() const;
```

etc.

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/LinSolverIterativeRandFGMRES.hpp
> +    index_type getConvCond();
```suggestion
    index_type getMaxit() const;
    index_type getRestart() const;
    index_type getConvCond() const;
```

etc.

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/RandSketchingManager.hpp
> +      virtual index_type getPaddedSize();
```suggestion
      virtual index_type getVectorSize() const;
      virtual index_type getSketchSize() const;
      virtual index_type getPaddedSize() const;
```

2023-11-29 14:53 UTC, cameronrutherford commented on resolve/cuda/cudaKernels.cu
> +#include <cooperative_groups.h>
Is this for atomic operations?

2023-11-29 14:53 UTC, cameronrutherford commented on runResolveOneMatrix
> +#!/bin/bash
I don't like adding too many of these misc scripts and prefer adding to testing infra directly where possible.

2023-11-29 15:12 UTC, pelesh commented on examples/r_randGMRES.cpp
> +  real_type* x   = nullptr;
You are absolutely right. AFAIK GPU data needs to use raw pointers, but elsewhere we could take advantage of shared/unique pointers. To be tracked in #88.

2023-11-29 15:15 UTC, pelesh commented on resolve/LinSolverIterativeFGMRES.cpp
> +    printf("it 0: norm %16.16e \n", rnorm);
This line has to go away. We have `Logger` class that can be conditionally disabled. @kswirydo, please remove or replace with Logger stream.

2023-11-29 15:16 UTC, pelesh commented on resolve/LinSolverIterativeFGMRES.cpp
> +        printf("it %d: norm %16.16e \n",it, rnorm);
Use `Logger` instead or remove.

2023-11-29 15:26 UTC, pelesh commented on resolve/LinSolverIterativeFGMRES.hpp
> +    bool getFlexible();
Tracked in #89

2023-11-29 15:26 UTC, pelesh commented on resolve/LinSolverIterativeFGMRES.hpp
>      real_type getInitResidualNorm();
Tracked in #89

2023-11-29 15:26 UTC, pelesh commented on resolve/LinSolverIterativeRandFGMRES.hpp
> +    index_type getConvCond();
See #89

2023-11-29 15:27 UTC, pelesh commented on resolve/RandSketchingManager.hpp
> +      virtual index_type getPaddedSize();
See #89

2023-11-29 15:39 UTC, kswirydo commented on resolve/LinSolverDirectRocSparseILU0.cpp
> +    mem_.allocateBufferOnDevice(&buffer_, buffer_size);
this is removed now - I allocate 3 separate buffers in the new version

2023-11-29 15:42 UTC, kswirydo commented on resolve/cuda/cudaKernels.cu
> +#include <cooperative_groups.h>
No. This stuff allows you to synchronize smaller groups of treads (not the entire block). It was added not that long ago. [See here](https://developer.nvidia.com/blog/cooperative-groups/)

2023-11-29 15:51 UTC, kswirydo commented on resolve/CMakeLists.txt
> +    LinSolverDirectCuSparseILU0.hpp
I dont know how to do it in cmake.

2023-11-29 16:06 UTC, cameronrutherford commented on resolve/CMakeLists.txt
> +    LinSolverDirectCuSparseILU0.hpp
https://github.com/ORNL/ReSolve/blob/develop/resolve/CMakeLists.txt#L76 - we have examples of CUDA / ROCm conditionals already in code

2023-11-29 16:18 UTC, kswirydo commented on runResolveOneMatrix
> +#!/bin/bash
removed

2023-11-29 16:18 UTC, kswirydo commented on resolve/LinSolverIterativeFGMRES.cpp
> +    printf("it 0: norm %16.16e \n", rnorm);
addressed in newest commit

2023-11-29 16:19 UTC, kswirydo commented on resolve/LinSolverIterativeFGMRES.cpp
> +        printf("it %d: norm %16.16e \n",it, rnorm);
addressed in newest commit

2023-11-29 16:43 UTC, ryandanehy commented
@kswirydo to get this to run PNNL tests the pr conflicts need to be fixed (probally best to do it through rebase). Then PNNL tests should start running.

2023-11-29 17:02 UTC, pelesh commented
> @kswirydo to get this to run PNNL tests the pr conflicts need to be fixed (probally best to do it through rebase). Then PNNL tests should start running.

It seems all we needed was to rebase to `develop`, not sure why.

2023-11-29 17:09 UTC, pelesh commented on resolve/LinSolverDirectRocSparseILU0.hpp
> +
Do we need roctracer here?
```suggestion

```

2023-11-29 17:10 UTC, pelesh commented on resolve/LinSolverDirectRocSparseILU0.hpp
> +
This trips tests on Incline, I am not sure how other tests pass.

2023-11-29 17:14 UTC, ryandanehy commented on resolve/LinSolverDirectRocSparseILU0.hpp
> +
Could have something to do with incline build env. Just a guess though.

2023-11-29 17:17 UTC, ryandanehy commented on resolve/LinSolverDirectRocSparseILU0.hpp
> +
@cameronrutherford  any ideas?

2023-11-29 17:19 UTC, pelesh commented on resolve/CMakeLists.txt
> +    LinSolverDirectCuSparseILU0.hpp
@cameronrutherford, I think we are okay here. We decided to install all header files for all configurations regardless. If you scroll a few lines up following the link you provided and you will find it there, as well. We could change the CMake code to install only headers that have matching libraries built (that would be a better solution I think). I will spawn another issue.

2023-11-29 17:20 UTC, cameronrutherford commented on resolve/LinSolverDirectRocSparseILU0.hpp
> +
Nuke header per #68

2023-11-29 17:21 UTC, pelesh commented on resolve/CMakeLists.txt
> +    LinSolverDirectCuSparseILU0.hpp
Tracked in #91.

2023-11-29 17:29 UTC, pelesh commented on resolve/LinSolverDirectRocSparseILU0.hpp
> +
> Nuke header per #68

@kswirydo, you have the honor ...

2023-11-29 17:45 UTC, pelesh commented on resolve/LinSolverDirectRocSparseILU0.cpp
> +    mem_.allocateBufferOnDevice(&buffer_, buffer_size);
I believe this could be much nicer fix for the conversion warnings:
```suggestion
    size_t buffer_size = std::max(buffer_size_A, std::max(buffer_size_L, buffer_size_U));
```

2023-11-29 17:47 UTC, pelesh commented on resolve/LinSolverDirectRocSparseILU0.cpp
> +    mem_.allocateBufferOnDevice(&buffer_, buffer_size);
CC @cameronrutherford

2023-11-29 17:48 UTC, pelesh commented on resolve/LinSolverDirectRocSparseILU0.cpp
> +    mem_.allocateBufferOnDevice(&buffer_, buffer_size);
I will resolve this thread in favor of the new one with proposed solution.

2023-11-29 17:58 UTC, pelesh requested changes
Remaining items before this can be merged:
- [x] Add functionality tests for randomized (F)GMRES on AMD and NVIDIA GPUs
- [x] Use STL math on the host (this will take care of a big chunk of warnings)
- [x] Fix other warnings
- [x] Remove `roctx.h` header from `LinSolverDirectRocSparseILU0.hpp`.

Almost there ;)

2023-11-30 20:45 UTC, cameronrutherford commented
> I fixed our little mishap with rebasing. All is needed to do is to:
> 
> * Generate test matrices _inside_ functionality tests. This is lesser evil than keeping 170MB test matrix in a repo.
> * Add again randomized solvers tests to CMake build and testing.

GitHub shouldn't allow files that big. pre-commit can also help detect when these large files are added, and custom thresholds can be configured cc @ryandanehy

2023-12-02 03:38 UTC, pelesh approved these changes
All review issues have been addressed. Merge once CI tests pass.

2023-12-02 03:52 UTC, merged