Implement system solver class
ORNL/ReSolve pull request #86
Opened 2023-11-29 00:05 UTC by pelesh

The system solver is supposed to be a high-level API for ReSolve. This class should also manage options settings.

This PR delivers main functionality for the `SystemSolver` class. It includes:
- Basic methods for parameter settings.
- Adjustments to linear solver classes interfaces.
- Removes loophole in functionality tests that could lead to false positives.
- Adds functionality tests and usage examples for `SystemSolver` class.
- Closes: #95.

2023-12-02 04:04 UTC, kswirydo requested changes
will compile and run next.

2023-12-02 04:04 UTC, kswirydo commented on resolve/SystemSolver.cpp
> +#ifdef RESOLVE_USE_CUDA
what about `cusolverRf` ????

2023-12-02 04:07 UTC, pelesh commented on resolve/SystemSolver.hpp
> +      real_type getFinalResidualNorm();
These are functions that access same methods in `LinSolverIterative` class.

2023-12-02 04:10 UTC, pelesh commented on resolve/SystemSolver.hpp
> +      LinSolverDirect* KLU_{nullptr};
You are right. I replace it with `factorizationSolver_`.

2023-12-02 04:12 UTC, pelesh commented on resolve/SystemSolver.hpp
> +      int irMaxit_{100};
So, should we then always allocate iterative solver and set max iterations to 0 if we don't want IR? Right now, I am passing string "none" for the refinement method to turn off IR.

2023-12-02 04:15 UTC, pelesh commented on tests/functionality/testKLU_RocSolver_FGMRES.cpp
> +  // TODO: Investigate why results are different when using Rf->solve(vec_x) !!
This is probably a bug somewhere in the code outside the scope of this PR.

2023-12-02 04:16 UTC, pelesh commented on examples/r_SysSolverCuda.cpp
> +  ReSolve::LinAlgWorkspaceCUDA* workspace_CUDA = new ReSolve::LinAlgWorkspaceCUDA;
I would need to bring back the workspace factory to do that. Removing it was a mistake in hindsight.

2023-12-02 04:18 UTC, pelesh commented on resolve/LinSolver.cpp
> +    return 1;
This function needs to be overridden, that is why it is returning an error. We should make it pure virtual, so it produces compilation error if it is not overridden by a child class.

2023-12-02 04:18 UTC, kswirydo commented on resolve/SystemSolver.hpp
> +      int irMaxit_{100};
Not sure. Can stay for now.

2023-12-02 04:21 UTC, pelesh commented on resolve/LinSolver.cpp
> +  void LinSolverDirect::setHaltIfSingular(bool isHalt)
I am guessing other direct solvers might have such function, as well. For now, I would like to keep it there. Otherwise, it would be difficult to set this parameter from the `SystemSolver` class.

2023-12-02 04:23 UTC, pelesh commented on resolve/LinSolver.cpp
> +  int LinSolverIterative::resetMatrix(matrix::Sparse* /* A */)
I am not sure if this method needs to be overridden or it can be fully implemented here.

2023-12-02 04:26 UTC, pelesh commented on resolve/LinSolver.hpp
> +      bool haltIfSingular_{false};
I am not sure, actually. Most direct solvers can use different orderings and specify pivot threshold. Most of them would also let you know if the matrix is singular after factorization.

2023-12-02 04:27 UTC, kswirydo commented on resolve/LinSolver.hpp
> +      bool haltIfSingular_{false};
well ordering and pivot threshold can stay, that `haltifsingular` is KLU-specific.

2023-12-02 04:31 UTC, pelesh commented on resolve/LinSolver.hpp
> +      real_type tol_{1e-14};
Good point. Perhaps replace with
```c++
real_type tol_{100*std::numeric_limits<real_type>::epsilon()};
```

2023-12-02 04:35 UTC, pelesh commented on resolve/LinSolver.hpp
> +      index_type restart_{10};
Same as with direct solvers -- it would be difficult to specify sets of parameters for each iterative solver implementation. The simplest solution would be for a solver that does not restart returns a warning if this parameter is set to > 0.

2023-12-02 04:37 UTC, pelesh commented on resolve/SystemSolver.hpp
> +      SystemSolver(std::string factorizationMethod, std::string refactorizationMethod, std::string solveMethod, std::string IRMethod);
I think that would be a good idea.

2023-12-02 04:41 UTC, pelesh commented on resolve/SystemSolver.hpp
> +      LinSolverDirect* KLU_{nullptr};
Fixed in [b2f2432](https://github.com/ORNL/ReSolve/pull/86/commits/b2f2432585f190440889b5b9b36decf6cea2c38c)

2023-12-02 04:46 UTC, pelesh commented on resolve/SystemSolver.cpp
> +#ifdef RESOLVE_USE_HIP
Examples should be easier to clean up. The system solver class on the other hand needs to hide discrepancies in APIs of different vendor functions.

2023-12-02 04:48 UTC, pelesh commented on resolve/SystemSolver.cpp
> +    // TODO: delete the matrix and all the solvers and all their workspace
We don't delete the matrix in `SystemSolver` class. Addressed in [40a35b6](https://github.com/ORNL/ReSolve/pull/86/commits/40a35b6ed97d6166788fc52bb0c8ba7a5b92bf1c).

2023-12-02 04:50 UTC, pelesh commented on resolve/SystemSolver.cpp
> +      if (gsMethod_ == "cgs2") {
Yes, it is. The question is, should we then expose enums to users?

2023-12-02 04:53 UTC, pelesh commented on resolve/SystemSolver.cpp
> +#ifdef RESOLVE_USE_CUDA
It is on my to-do list, I didn't plan it for this PR, but can add it.

2023-12-02 05:01 UTC, pelesh commented on resolve/SystemSolver.cpp
> +        status = KLU_->solve(rhs, x);
It works with GLU _and_ rocsolverRf because they set flag `isSolveOnDevice_` differently. See function `refactorize_setup`.

2023-12-02 05:01 UTC, pelesh commented on resolve/SystemSolver.cpp
> +        status = KLU_->solve(rhs, x);
See previous explanation.

2023-12-02 21:11 UTC, pelesh commented on resolve/LinSolver.cpp
> +  void LinSolverDirect::setHaltIfSingular(bool isHalt)
Handling parameter settings in ReSolve is nontrivial issue given the complexity of the code. I suggest for now to create groups of direct and iterative solver parameters. Each group will be a superset of parameters for all solvers in the group. This is a short term solution. Let's discuss more long-term options in #96.

2023-12-02 21:13 UTC, pelesh commented on resolve/LinSolver.hpp
> +      bool haltIfSingular_{false};
See #96.

2023-12-02 21:13 UTC, pelesh commented on resolve/LinSolver.hpp
> +      index_type restart_{10};
Also see #96.

2023-12-02 21:14 UTC, pelesh commented on resolve/LinSolverIterativeFGMRES.hpp
> -    void setRestart(index_type new_restart);
I suggest continuing discussion in #96 and addressing this issue in a separate PR.

2023-12-02 23:41 UTC, pelesh commented on resolve/LinSolver.cpp
> +  int LinSolverIterative::resetMatrix(matrix::Sparse* /* A */)
After checking, this method needs to be overridden by the child class. Otherwise, we would need the base class to own a pointer to the matrix handler. This might be something to consider, as well.

2023-12-02 23:43 UTC, pelesh commented on resolve/LinSolver.cpp
> +    return 1;
After reviewing all the options, I think this is the best solution right now. Not all direct solver implement `refactorize` method, so we need a default implementation that will return failure if called.

2023-12-03 17:56 UTC, pelesh commented on resolve/SystemSolver.hpp
> +      const std::string getFactorizationMethod() const;
Agreed, but suggest we handle it in separate PR. See #96.

2023-12-04 22:51 UTC, pelesh commented on resolve/SystemSolver.hpp
> +      real_type getFinalResidualNorm();
This has been addressed in [d5fb0df](https://github.com/ORNL/ReSolve/pull/86/commits/d5fb0df670313d09db303038543c34d513790794).

2023-12-05 03:30 UTC, kswirydo reviewed
So both syssolver test with cuda and klu_glu test gives this (for the first matrix) which is obviously wrong 
	 ||b-A*x||_2                 : 2.88790648555419e-12 (residual norm)
	 ||b-A*x||_2  (CPU)          : 2.483452223531182e-12 (residual norm)
	 ||b-A*x||_2/||b||_2         : 1.465835083417962e-18 (scaled residual norm)
	 ||x-x_true||_2              : 5.382658656691419e-12 (solution error)
	 ||x-x_true||_2/||x_true||_2 : 7.898611154542518e-14 (scaled solution error)
	 ||b-A*x_exact||_2           : 1970144.198500361 (control; residual norm with exact solution)
	 (I fixed this, see the newest commit)
	 All other tested exampleswork.

2023-12-05 03:45 UTC, pelesh commented on examples/r_KLU_GLU.cpp
> +    //   KLU->setupParameters(1, 0.1, false);
This method has been removed from the `LinSolverDirectKLU` class. Will remove comments.

2023-12-05 03:48 UTC, pelesh commented on resolve/LinSolver.cpp
> -  int LinSolverIterative::solve(vector_type* /* rhs */, vector_type* /* init_guess */)
`solve` is pure virtual now, so it does not need implementation.

2023-12-05 03:50 UTC, pelesh commented on resolve/LinSolver.hpp
> +      bool getFlexible();
Base iterative solver class for now contains superset of parameters for all implemented iterative solvers. This is not a long term solution and parameter settings for all solvers will be handled outside this PR.

2023-12-05 03:52 UTC, pelesh commented on resolve/LinSolver.hpp
> -      virtual int  solve(vector_type* rhs, vector_type* init_guess);
It was just moved :)

2023-12-05 03:53 UTC, pelesh commented on resolve/LinSolverIterativeRandFGMRES.hpp
>      void getRandSketchingMethod(std::string rand_method);
This was not part of this PR. Track this in #99.

2023-12-05 03:54 UTC, pelesh commented on tests/functionality/testKLU.cpp
> -  KLU->setupParameters(1, 0.1, false);
Method was removed from `LinSolverDirectKLU` class.

2023-12-05 03:56 UTC, pelesh commented on tests/functionality/testKLU_RocSolver_FGMRES.cpp
> +  // TODO: 1e-9 is too lose acuracy!
Rocsolver is reproducible. This TODO still applies.

2023-12-05 03:56 UTC, pelesh commented on tests/functionality/testSysHipRefine.cpp
> +  std::cout<<"Results (first matrix): "<<std::endl<<std::endl;
Yes, it does.

2023-12-05 04:00 UTC, pelesh commented on resolve/SystemSolver.cpp
> +      out::warning() << "Factorization failed ...\n";
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:01 UTC, pelesh commented on resolve/LinSolver.hpp
> +      index_type fgmres_iters_;
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:01 UTC, pelesh commented on examples/r_KLU_rocsolverrf_redo_factorization.cpp
> +    // if (i == 0) {
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:01 UTC, pelesh commented on examples/r_KLU_rocsolverrf.cpp
> +    //   KLU->setupParameters(1, 0.1, false);
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:01 UTC, pelesh commented on examples/r_KLU_rocSolverRf_FGMRES.cpp
> +    // if (i == 0) {
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:01 UTC, pelesh commented on examples/r_KLU_rf_FGMRES_reuse_factorization.cpp
> +    // if (i == 0) {
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:01 UTC, pelesh commented on examples/r_KLU_rf_FGMRES.cpp
> +    // if (i == 0) {
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:02 UTC, pelesh commented on examples/r_KLU_rf.cpp
> +    // if (i == 0) {
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:02 UTC, pelesh commented on examples/r_KLU_KLU_standalone.cpp
> +  // KLU->setupParameters(1, 0.1, false);
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:02 UTC, pelesh commented on examples/r_KLU_KLU.cpp
> +    // if (i == 0) {
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:02 UTC, pelesh commented on examples/r_KLU_GLU_matrix_values_update.cpp
> +      // if (i == 0) {
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:02 UTC, pelesh commented on examples/r_KLU_GLU.cpp
> +    //   KLU->setupParameters(1, 0.1, false);
Addressed in [fd7292e](https://github.com/ORNL/ReSolve/pull/86/commits/fd7292eac328c8fdac64a1a2b97a70fd15698514).

2023-12-05 04:03 UTC, pelesh commented on resolve/SystemSolver.cpp
> +    if (refactorizationMethod_ == "glu") {
Will be implemented in separate PR.

2023-12-05 04:05 UTC, pelesh commented on resolve/vector/Vector.cpp
> +  int Vector::update(Vector* v, memory::MemorySpace memspaceIn, memory::MemorySpace memspaceOut)
Will be taken care of in separate PR.

2023-12-05 04:46 UTC, merged